license = "AGPL-3.0"
modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Taiyou06/meg-client-mod/issues"

[[mods]]
modId = "${id}"
displayName = "${name}"
version = "${version}"
authors = "Taiyouh"
description = "A client-side mod that decodes ModelEngine's optimized bulk entity-data packet into vanilla Display updates."

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"
